#multi stage build
FROM node:11-alpine AS builder
WORKDIR /app

COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

COPY . /app

RUN ng build --configuration=develop
#for production
#RUN ng build --configuration=production

FROM djay921/nginxopenshift:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8081

COPY --from=builder /app/dist/EconomicSimulation /usr/share/nginx/html

