FROM nginx:1.14.0
RUN  apt update && apt install apache2-utils -y
WORKDIR /etc/apache2
RUN echo "ello"
RUN htpasswd -b -c /etc/apache2/.htpasswd admin admin
RUN cat /etc/apache2/.htpasswd
RUN chmod 777  /etc/apache2/.htpasswd
