FROM node:10 as base
WORKDIR /app
COPY package.json .
RUN mkdir logs
RUN npm install

FROM node:10-alpine
WORKDIR /app
EXPOSE 8000
COPY --from=base /app/node_modules /app/node_modules
COPY . .
RUN  npm rebuild node-sass && npm run build
run ls -lrt
RUN chmod -R 777 /app
#CMD [ "npm", "start" ]
CMD node --max-old-space-size=8192 server/app.js
