FROM ubuntu:18.04

#********************************************** ENVIRONMENT VARIABLES *****************************************
ENV PYTHONIOENCODING=utf-8
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONUNBUFFERED 1

#*************************************************** WORKING DIRECTORY ***************************************
WORKDIR /home

RUN apt-get update && apt-get install -y wget openjdk-8-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
RUN apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get install -y python3.6 python3-pip
RUN ln -sfn /usr/bin/python3.6 /usr/bin/python3 && ln -sfn /usr/bin/python3 /usr/bin/python && ln -sfn /usr/bin/pip3 /usr/bin/pip

RUN apt-get -y install ghostscript icc-profiles-free liblept5 libxml2 pngquant
RUN apt install python-poppler poppler-utils tesseract-ocr tesseract-ocr-deu ocrmypdf nano -y                                                                               
RUN wget https://github.com/pdf2htmlEX/pdf2htmlEX/releases/download/v0.16.0-poppler-0.62.0-ubuntu-18.04/pdf2htmlex_0.16.0-1.git201909191126r32f7c-0ubuntu1.bionic1_amd64.deb
RUN apt install -y ./pdf2htmlex_0.16.0-1.git201909191126r32f7c-0ubuntu1.bionic1_amd64.deb


